name: organaki_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_map: ^3.1.0
  flutter_bloc: ^8.1.2
  result_dart: ^1.0.6
  latlong2: ^0.8.1
  latlng: ^1.0.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
     - images/
  #   Put the images inside folder images


